#!/bin/bash

# First of all we will stop stopped all the docker container by their name
docker stop $(docker ps -a -q)

# After that we will delete all stopped container
docker rm $(docker ps -a -q)

# The above command line will stop and delete all container, please be carreful.